ACHIEVEMENTS = [
    {
        'key': 'first_task',
        'name': 'First Step',
        'description': 'Complete your first task',
        'icon': '✅',
        'xp_reward': 20,
    },
    {
        'key': 'ten_tasks',
        'name': 'On a Roll',
        'description': 'Complete 10 tasks',
        'icon': '🔥',
        'xp_reward': 50,
    },
    {
        'key': 'fifty_tasks',
        'name': 'Task Master',
        'description': 'Complete 50 tasks',
        'icon': '⚡',
        'xp_reward': 150,
    },
    {
        'key': 'first_habit',
        'name': 'Creature of Habit',
        'description': 'Log a habit for the first time',
        'icon': '🌱',
        'xp_reward': 20,
    },
    {
        'key': 'habit_streak_7',
        'name': 'Week Warrior',
        'description': 'Maintain a 7-day habit streak',
        'icon': '🗓️',
        'xp_reward': 50,
    },
    {
        'key': 'habit_streak_30',
        'name': 'Unstoppable',
        'description': 'Maintain a 30-day habit streak',
        'icon': '💎',
        'xp_reward': 200,
    },
    {
        'key': 'first_focus',
        'name': 'In the Zone',
        'description': 'Complete your first focus session',
        'icon': '🎯',
        'xp_reward': 20,
    },
    {
        'key': 'ten_focus',
        'name': 'Deep Worker',
        'description': 'Complete 10 focus sessions',
        'icon': '🧠',
        'xp_reward': 75,
    },
    {
        'key': 'first_project',
        'name': 'Project Starter',
        'description': 'Create your first project',
        'icon': '📁',
        'xp_reward': 20,
    },
    {
        'key': 'level_5',
        'name': 'Rising Star',
        'description': 'Reach Level 5',
        'icon': '⭐',
        'xp_reward': 100,
    },
    {
        'key': 'level_10',
        'name': 'Veteran',
        'description': 'Reach Level 10',
        'icon': '🏆',
        'xp_reward': 250,
    },
]